using UnityEngine;
using UnityEditor;
using System.IO;

public class AutoPrefabExporter : EditorWindow {
    private const string rootObjectName = "Human";

    // デフォルト値（起動時にEditorPrefsから読み込まれる）
    public static string prefabFolderInAssets = "Assets/AutoGeneratedPrefabs";
    public static string packageOutputDirectory = "";
    public static string packageFileName = "ExportedPackage.unitypackage";

    [MenuItem("Tools/Auto Export Prefab Window")]
    public static void ShowWindow() {
        GetWindow<AutoPrefabExporter>("Auto Prefab Exporter");
    }

    void OnEnable() {
        // EditorPrefsから前回の設定を読み込む
        prefabFolderInAssets = EditorPrefs.GetString("AutoExport_PrefabFolder", "Assets/AutoGeneratedPrefabs");
        packageOutputDirectory = EditorPrefs.GetString("AutoExport_PackageFolder", "");
        packageFileName = EditorPrefs.GetString("AutoExport_FileName", "ExportedPackage.unitypackage");
    }

    void OnGUI() {
        GUILayout.Label("Prefab出力（プロジェクト内）", EditorStyles.boldLabel);
        string newPrefabPath = EditorGUILayout.TextField("Prefabフォルダ（Assets内）", prefabFolderInAssets);
        if (newPrefabPath != prefabFolderInAssets) {
            prefabFolderInAssets = newPrefabPath;
            EditorPrefs.SetString("AutoExport_PrefabFolder", prefabFolderInAssets);
        }

        GUILayout.Space(10);
        GUILayout.Label("UnityPackage 出力先（絶対パス）", EditorStyles.boldLabel);

        EditorGUILayout.BeginHorizontal();
        EditorGUILayout.SelectableLabel(packageOutputDirectory, GUILayout.Height(16));
        if (GUILayout.Button("フォルダ選択", GUILayout.Width(100))) {
            string selected = EditorUtility.OpenFolderPanel("unitypackageの出力先を選択", Application.dataPath, "");
            if (!string.IsNullOrEmpty(selected)) {
                packageOutputDirectory = selected;
                EditorPrefs.SetString("AutoExport_PackageFolder", packageOutputDirectory);
            }
        }
        EditorGUILayout.EndHorizontal();

        string newFileName = EditorGUILayout.TextField("ファイル名", packageFileName);
        if (newFileName != packageFileName) {
            packageFileName = newFileName;
            EditorPrefs.SetString("AutoExport_FileName", packageFileName);
        }

        GUILayout.Space(20);
        if (GUILayout.Button("🚀 Export Prefab & UnityPackage")) {
            Export();
        }
    }

    public static void Export() {
        GameObject target = GameObject.Find(rootObjectName);
        if (target == null) {
            Debug.LogError($"ヒエラルキーに '{rootObjectName}' という名前のGameObjectが見つかりません。");
            return;
        }

        // プレハブ保存
        if (!Directory.Exists(prefabFolderInAssets)) {
            Directory.CreateDirectory(prefabFolderInAssets);
        }

        string prefabPath = $"{prefabFolderInAssets}/{target.name}.prefab";
        PrefabUtility.SaveAsPrefabAssetAndConnect(target, prefabPath, InteractionMode.UserAction);
        PrefabUtility.UnpackPrefabInstance(target, PrefabUnpackMode.Completely, InteractionMode.UserAction);

        // unitypackage保存
        if (string.IsNullOrEmpty(packageOutputDirectory) || !Directory.Exists(packageOutputDirectory)) {
            Debug.LogError("UnityPackageの出力先フォルダが正しく設定されていません。");
            return;
        }

        string fullExportPath = Path.Combine(packageOutputDirectory, packageFileName);
        AssetDatabase.ExportPackage(prefabFolderInAssets, fullExportPath, ExportPackageOptions.Recurse);

        Debug.Log($"Export完了\n- Prefab: {prefabPath}\n- UnityPackage: {fullExportPath}");
    }
}
